= Dell vRAN Lab *** Dell / Red Hat / Altiostar ***

== Infrastructure servers

=== RHHI

* management: +
rhvm.lab.roskosb.info +
https://rhvm.lab.roskosb.info/ +
admin / redhat

* packages and containers: +
satellite.lab.roskosb.info +
https://satellite.lab.roskosb.info +
admin /redhat 

* generic rhel7 guest +
rhel77-test.lab.roskosb.info +
root / redhat

* hosts: +
rhhi-1.lab.roskosb.info +
rhhi-2.lab.roskosb.info +
rhhi-3.lab.roskosb.info +
root /redhat 

When specifying gluster volumes in gluster wizard, use the wwid value, which will differ for each rhhi host: +
rhhi1: /dev/mapper/36d0946602a4a8d0025826f2a6ac3f40a +
rhhi2: /dev/mapper/36d0946600f82750025826eda52da0537 +
rhhi3: /dev/mapper/36d094660106d090025826e62733a0e86 

virtual usb created at root of dell-lab folder has ifcfg files for rhhi hosts +
attach virtual media via idrac +
mount on rhhi node: +
mkdir /media/usb
mount -o loop,ro,noexec,noload /dev/sdc1 /media/usb/ +
then copy files from /media/usb/{rhhi hostname} to /etc/sysconfig/network-scripts 

RHHI servers have a hard dependency on DNS, avoid trying to use /etc/hosts, it just causes problems later on. 

Compute nodes need to resolve satellite server by name.

Enabled dns proxy on satellite,


....
satellite-installer --scenario satellite --foreman-initial-organization lab --foreman-initial-admin-password redhat --foreman-initial-location tewksbury --foreman-initial-admin-username admin --foreman-proxy-dns true
....
edit /etc/named/options.conf to set: +
allow-recursion { any; }; +
restart named

overcloud has a hard dependency on NTP, computes can't access the internet, so make sure NTP is available internally. Using RHHI servers for internal NTP. +
- to enable, add to /etc/chrony.conf +
allow 192.168.0.0/16 +
allow 172.17.0.0/16 +
- add ntp service to firewalld

== OpenStack

* director: +
director.lab.roskosb.info +
stack / redhat

* horizon: +
http://overcloud.lab.roskosb.info +
see vranlabrc file for credentials