resource_registry:
# Configure Networks
  OS::TripleO::Controller::Net::SoftwareConfig:
    ../network/config/multiple-nics/controller.yaml
  OS::TripleO::Compute::Net::SoftwareConfig:
    ../network/config/bond-with-vlans/compute.yaml
  OS::TripleO::ComputeHCI::Net::SoftwareConfig:
    ../network/config/bond-with-vlans/compute-hci.yaml
  OS::TripleO::ComputeEdge1::Net::SoftwareConfig:
    ../network/config/bond-with-vlans/compute-e1.yaml
  OS::TripleO::ComputeEdge1vdu::Net::SoftwareConfig:
    ../network/config/bond-with-vlans/compute-e1vdu.yaml
  OS::TripleO::ComputeEdge2::Net::SoftwareConfig:
    ../network/config/bond-with-vlans/compute-e2.yaml
  OS::TripleO::ComputeEdge2vdu::Net::SoftwareConfig:
    ../network/config/bond-with-vlans/compute-e2vdu.yaml

parameter_defaults:
  DnsServers:
  - 172.17.118.8
  NtpServer:
  - 172.17.118.1
  - 172.17.118.3
  - 172.17.118.5
  BondInterfaceOvsOptions: "mode=4 miimon=100"

  DockerInsecureRegistryAddress:
  - 172.17.118.8:5000
  - satellite.lab.roskosb.info:5000

  ControllerControlPlaneSubnet: leaf0
  ComputeControlPlaneSubnet: leaf0
  ComputeHCIControlPlaneSubnet: leaf0
  ComputeEdge1ControlPlaneSubnet: edge1
  ComputeEdge1vduControlPlaneSubnet: edge1
  ComputeEdge2ControlPlaneSubnet: edge2
  ComputeEdge2vduControlPlaneSubnet: edge2
  VipSubnetMap:
    ctlplane: leaf0

#  ControlPlaneSubnetCidr: '26'
#  ControlPlaneSubnet: leaf0
#  ControlPlaneDefaultRoute: 192.168.120.62

  NeutronNetworkType: 'vxlan,vlan'
  NeutronTunnelTypes: ''
  NeutronNetworkVLANRanges:
    - management:117:117
    - sriov-1:200:300
    - sriov-2:200:300
    - fronthaul-1:200:300
    - fronthaul-2:200:300
  NeutronFlatNetworks:
    - floating-ips

  NeutronBridgeMappings:
    - tenant:br-tenant
    - datacentre:br-ex
    - management:br-mgmt
    - floating-ips:br-float

  CloudName: overcloud.lab.roskosb.info
#  CloudDomain: lab.roskosb.info

  NeutronEnableIsolatedMetadata: true
  NeutronEnableForceMetadata: true
  NeutronEnableMetadataNetwork: true
#  NeutronGlobalPhysnetMtu: 9000

  NovaReservedHostMemory: 4096
  OvercloudControllerFlavor: control
  OvercloudComputeFlavor: compute
  OvercloudComputeHCIFlavor: compute-hci
  OvercloudComputeEdge1Flavor: compute-edge1
  OvercloudComputeEdge1vduFlavor: compute-edge1vdu
  OvercloudComputeEdge2Flavor: compute-edge2
  OvercloudComputeEdge2vduFlavor: compute-edge2vdu
  ControllerCount: 3
  ComputeCount: 2
  ComputeHCICount: 3
  ComputeEdge1Count: 1
  ComputeEdge1vduCount: 1
  ComputeEdge2Count: 1
  ComputeEdge2vduCount: 1

  NovaSchedulerDefaultFilters:
    - RetryFilter
    - AvailabilityZoneFilter
    - ComputeFilter
    - AggregateInstanceExtraSpecsFilter
    - ComputeCapabilitiesFilter
    - ImagePropertiesFilter
    - ServerGroupAntiAffinityFilter
    - ServerGroupAffinityFilter
    - PciPassthroughFilter
    - NUMATopologyFilter

  PublicVirtualFixedIPs: [{'ip_address':'172.17.119.10'}]

  ControllerExtraConfig:
    nova::cpu_allocation_ratio: 1
    nova::pci::aliases:
      - name: vc_fpga
        vendor_id: '1172'
        product_id: '5050'
        device_type: 'type-VF'

  ComputeParameters:
    KernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=128 intel_iommu=on iommu=pt"
    IsolCpusList: 2-35,38-71
    NovaComputeCpuDedicatedSet: 2-35,38-71
    NovaComputeCpuSharedSet: 0,1,36,37
    NeutronPhysicalDevMappings:
      - sriov-1:ens3f0
      - sriov-2:ens3f1
      - sriov-1:ens7f0
      - sriov-2:ens7f1
    NeutronSriovNumVFs:
      - ens3f0:8
      - ens3f1:8
      - ens7f0:8
      - ens7f1:8
    NovaPCIPassthrough:
      - devname: "ens3f0"
        physical_network: "sriov-1"
      - devname: "ens3f1"
        physical_network: "sriov-2"
      - devname: "ens7f0"
        physical_network: "sriov-1"
      - devname: "ens7f1"
        physical_network: "sriov-2"

  ComputeExtraConfig:
    nova::cpu_allocation_ratio: 1
    nova::compute::resume_guests_state_on_host_boot: true

#  ComputeHCIImage: "overcloud-full-hci"
  ComputeHCIParameters:
    KernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=128 intel_iommu=on iommu=pt"
    IsolCpusList: 2-35,38-71
    NovaComputeCpuDedicatedSet: 6-35,42-71
    NovaComputeCpuSharedSet: 0,1,36,37
    NovaReservedHostMemory: 30720
    NeutronPhysicalDevMappings:
      - sriov-1:ens3f0
      - sriov-2:ens3f1
      - sriov-1:ens7f0
      - sriov-2:ens7f1
    NeutronSriovNumVFs:
      - ens3f0:8
      - ens3f1:8
      - ens7f0:8
      - ens7f1:8
    NovaPCIPassthrough:
      - devname: "ens3f0"
        physical_network: "sriov-1"
      - devname: "ens3f1"
        physical_network: "sriov-2"
      - devname: "ens7f0"
        physical_network: "sriov-1"
      - devname: "ens7f1"
        physical_network: "sriov-2"

  ComputeHCIExtraConfig:
    nova::cpu_allocation_ratio: 1
    nova::compute::resume_guests_state_on_host_boot: true

  ComputeEdge1Parameters:
    KernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=128 intel_iommu=on iommu=pt"
    IsolCpusList: 2-35,38-71
    NovaComputeCpuDedicatedSet: 2-35,38-71
    NovaComputeCpuSharedSet: 0,1,36,37
    NovaEnableRbdBackend: false
    NeutronPhysicalDevMappings:
      - sriov-1:ens3f0
      - sriov-2:ens3f1
      - sriov-1:ens7f0
      - sriov-2:ens7f1
    NeutronSriovNumVFs:
      - ens3f0:8
      - ens3f1:8
      - ens7f0:8
      - ens7f1:8
    NovaPCIPassthrough:
      - devname: "ens3f0"
        physical_network: "sriov-1"
      - devname: "ens3f1"
        physical_network: "sriov-2"
      - devname: "ens7f0"
        physical_network: "sriov-1"
      - devname: "ens7f1"
        physical_network: "sriov-2"

  ComputeEdge1ExtraConfig:
    nova::cpu_allocation_ratio: 1
    nova::compute::resume_guests_state_on_host_boot: true
    nova::compute::libvirt::libvirt_cpu_model: host-passthrough
    nova::compute::libvirt::libvirt_cpu_model_extra_flags: host-tsc-deadline
    nova::compute::libvirt::mem_stats_period_seconds: 0

  ComputeEdge1vduImage: "overcloud-realtime-compute"
  ComputeEdge1vduParameters:
    KernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=128 nx_huge_pages_recovery_ratio=0 intel_iommu=on iommu=pt elevator=cfq audit=1 nomodeset intel_idle.max_cstate=1 tsc=reliable idle=poll rcu_nocb_poll=1 clocksource=tsc pcie_aspm.policy=performance"
    IsolCpusList: 2-35,38-71
    NovaComputeCpuDedicatedSet: 2-35,38-71
    NovaComputeCpuSharedSet: 0,1,36,37
    NovaEnableRbdBackend: false
    NeutronPhysicalDevMappings:
      - fronthaul-1:ens1f0
      - fronthaul-2:ens1f1
      - fronthaul-1:ens4f0
      - fronthaul-2:ens4f1
      - sriov-1:ens3f0
      - sriov-2:ens3f1
      - sriov-1:ens8f0
      - sriov-2:ens8f1
    NeutronSriovNumVFs:
      - ens3f0:8
      - ens3f1:8
      - ens8f0:8
      - ens8f1:8
      - ens1f0:8
      - ens1f1:8
      - ens4f0:8
      - ens4f1:8
    NovaPCIPassthrough:
      - devname: "ens1f0"
        physical_network: "fronthaul-1"
      - devname: "ens1f1"
        physical_network: "fronthaul-2"
      - devname: "ens4f0"
        physical_network: "fronthaul-1"
      - devname: "ens4f1"
        physical_network: "fronthaul-2"
      - devname: "ens3f0"
        physical_network: "sriov-1"
      - devname: "ens3f1"
        physical_network: "sriov-2"
      - devname: "ens8f0"
        physical_network: "sriov-1"
      - devname: "ens8f1"
        physical_network: "sriov-2"
      - vendor_id: "1172"
        product_id: "5050"

  ComputeEdge1vduExtraConfig:
    nova::cpu_allocation_ratio: 1
    nova::compute::resume_guests_state_on_host_boot: true
    nova::pci::aliases:
      - name: vc_fpga
        vendor_id: '1172'
        product_id: '5050'
        device_type: 'type-VF'

  ComputeEdge2Parameters:
    KernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=128 intel_iommu=on iommu=pt"
    IsolCpusList: 2-35,38-71
    NovaComputeCpuDedicatedSet: 2-35,38-71
    NovaComputeCpuSharedSet: 0,1,36,37
    NovaEnableRbdBackend: false
    NeutronPhysicalDevMappings:
      - sriov-1:ens3f0
      - sriov-2:ens3f1
      - sriov-1:ens7f0
      - sriov-2:ens7f1
    NeutronSriovNumVFs:
      - ens3f0:8
      - ens3f1:8
      - ens7f0:8
      - ens7f1:8
    NovaPCIPassthrough:
      - devname: "ens3f0"
        physical_network: "sriov-1"
      - devname: "ens3f1"
        physical_network: "sriov-2"
      - devname: "ens7f0"
        physical_network: "sriov-1"
      - devname: "ens7f1"
        physical_network: "sriov-2"

  ComputeEdge2ExtraConfig:
    nova::cpu_allocation_ratio: 1
    nova::compute::resume_guests_state_on_host_boot: true
    nova::compute::libvirt::libvirt_cpu_model: host-passthrough
    nova::compute::libvirt::libvirt_cpu_model_extra_flags: host-tsc-deadline
    nova::compute::libvirt::mem_stats_period_seconds: 0

  ComputeEdge2vduImage: "overcloud-realtime-compute"
  ComputeEdge2vduParameters:
    KernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=128 nx_huge_pages_recovery_ratio=0 intel_iommu=on iommu=pt elevator=cfq audit=1 nomodeset intel_idle.max_cstate=1 tsc=reliable idle=poll rcu_nocb_poll=1 clocksource=tsc pcie_aspm.policy=performance"
    IsolCpusList: 2-35,38-71
    NovaComputeCpuDedicatedSet: 2-35,38-71
    NovaComputeCpuSharedSet: 0,1,36,37
    NovaEnableRbdBackend: false
    NeutronPhysicalDevMappings:
      - fronthaul-1:ens1f0
      - fronthaul-2:ens1f1
      - fronthaul-1:ens4f0
      - fronthaul-2:ens4f1
      - sriov-1:ens3f0
      - sriov-2:ens3f1
      - sriov-1:ens8f0
      - sriov-2:ens8f1
    NeutronSriovNumVFs:
      - ens3f0:8
      - ens3f1:8
      - ens8f0:8
      - ens8f1:8
      - ens1f0:8
      - ens1f1:8
      - ens4f0:8
      - ens4f1:8
    NovaPCIPassthrough:
      - devname: "ens1f0"
        physical_network: "fronthaul-1"
      - devname: "ens1f1"
        physical_network: "fronthaul-2"
      - devname: "ens4f0"
        physical_network: "fronthaul-1"
      - devname: "ens4f1"
        physical_network: "fronthaul-2"
      - devname: "ens3f0"
        physical_network: "sriov-1"
      - devname: "ens3f1"
        physical_network: "sriov-2"
      - devname: "ens8f0"
        physical_network: "sriov-1"
      - devname: "ens8f1"
        physical_network: "sriov-2"
      - vendor_id: "1172"
        product_id: "5050"

  ComputeEdge2vduExtraConfig:
    nova::cpu_allocation_ratio: 1
    nova::compute::resume_guests_state_on_host_boot: true
    nova::pci::aliases:
      - name: vc_fpga
        vendor_id: '1172'
        product_id: '5050'
        device_type: 'type-VF'

  RhsmVars:
    rhsm_method: "satellite"
    rhsm_server_hostname: "satellite.lab.roskosb.info"
    rhsm_baseurl: "https://satellite.lab.roskosb.info/pulp/repos"
    rhsm_activation_key: "osp16-dev"
    rhsm_org_id: "lab"
    rhsm_force_register: True
