resource_registry:
# Configure Networks
  OS::TripleO::Controller::Net::SoftwareConfig:
    ../network/config/multiple-nics/controller.yaml
  OS::TripleO::Compute::Net::SoftwareConfig:
    ../network/config/single-nic-vlans/compute.yaml
  OS::TripleO::ComputeHCI::Net::SoftwareConfig:
    ../network/config/single-nic-vlans/compute-hci.yaml
  OS::TripleO::ComputeEdge1::Net::SoftwareConfig:
    ../network/config/single-nic-vlans/compute-e1.yaml
  OS::TripleO::ComputeEdge1vdu::Net::SoftwareConfig:
    ../network/config/single-nic-vlans/compute-e1.yaml
  OS::TripleO::ComputeEdge2::Net::SoftwareConfig:
    ../network/config/single-nic-vlans/compute-e2.yaml
  OS::TripleO::ComputeEdge2vdu::Net::SoftwareConfig:
    ../network/config/single-nic-vlans/compute-e2.yaml

parameter_defaults:
  DnsServers:
  - 172.17.118.8
  NtpServer:
  - 172.17.118.1
  - 172.17.118.3
  - 172.17.118.5
  EC2MetadataIp: 192.168.120.5
  NeutronExternalNetworkBridge: "''"
  BondInterfaceOvsOptions: "mode=4 miimon=100"
  DockerInsecureRegistryAddress:
  - 172.17.118.8:5000
  - satellite.lab.roskosb.info:5000

  ControllerControlPlaneSubnet: leaf0
  ComputeControlPlaneSubnet: leaf0
  ComputeHCIControlPlaneSubnet: leaf0
  ComputeEdge1ControlPlaneSubnet: edge1
  ComputeEdge1vduControlPlaneSubnet: edge1
  ComputeEdge2ControlPlaneSubnet: edge2
  ComputeEdge2vduControlPlaneSubnet: edge2

  ControlPlaneSubnetCidr: '26'
  ControlPlaneSubnet: leaf0
  ControlPlaneDefaultRoute: 192.168.120.62
  ControlPlaneEdge1DefaultRoute: 192.168.120.126
  ControlPlaneEdge1SubnetCidr: '26'
  ControlPlaneEdge2DefaultRoute: 192.168.120.190
  ControlPlaneEdge2SubnetCidr: '26'

  NeutronBridgeMappings:
  - tenant:br-tenant
  - datacentre:br-ex

#  NeutronNetworkVLANRanges:
#    - tenant:1000:2000
#    - provider:1000:2000
#    - leaf2:1000:1000
#    - edge1:1000:1000

  InternalApiSupernet: 192.168.130.0/24
  TenantSupernet: 192.168.201.0/24
  ControlPlaneSupernet: 192.168.120.0/24

  CloudName: overcloud.lab.roskosb.info
  CloudDomain: lab.roskosb.info

  NeutronEnableIsolatedMetadata: true
  NeutronEnableForceMetadata: true
  NeutronEnableMetadataNetwork: true
#  NeutronGlobalPhysnetMtu: 9000

  NovaReservedHostMemory: 4096
  OvercloudControllerFlavor: control
  OvercloudComputeFlavor: compute
  OvercloudComputeHCIFlavor: compute-hci
  OvercloudComputeEdge1Flavor: compute-edge1
  OvercloudComputeEdge1vduFlavor: compute-edge1vdu
  OvercloudComputeEdge2Flavor: compute-edge2
  OvercloudComputeEdge2vduFlavor: compute-edge2vdu
  ControllerCount: 3
  ComputeCount: 3
  ComputeHCICount: 1
  ComputeEdge1Count: 2
  ComputeEdge1vduCount: 1
  ComputeEdge2Count: 0
  ComputeEdge2vduCount: 1

  NovaSchedulerDefaultFilters:
    - RetryFilter
    - AvailabilityZoneFilter
    - AggregateRamFilter
    - AggregateCoreFilter
    - ComputeFilter
    - AggregateInstanceExtraSpecsFilter
    - ComputeCapabilitiesFilter
    - ImagePropertiesFilter
    - ServerGroupAntiAffinityFilter
    - ServerGroupAffinityFilter
    - RamFilter
    - DiskFilter

  PublicVirtualFixedIPs: [{'ip_address':'172.17.119.10'}]

  ComputeParameters:
    KernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=128 intel_iommu=on iommu=pt"
    IsolCpusList: 2-35,38-71
    NovaVcpuPinSet: 2-35,38-71

  ComputeHCIParameters:
    KernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=128 intel_iommu=on iommu=pt"
    IsolCpusList: 2-35,38-71
    NovaVcpuPinSet: 6-35,42-71
    NovaReservedHostMemory: 30720

  ComputeHCIExtraConfig:
    nova::cpu_allocation_ratio: 1

  ComputeEdge1Parameters:
    KernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=128 intel_iommu=on iommu=pt"
    IsolCpusList: 2-35,38-71
    NovaVcpuPinSet: 2-35,38-71

  ComputeEdge1ExtraConfig:
    nova::compute::libvirt::vncserver_listen: "%{hiera('internal_api_edge1')}"
    nova::compute::vncserver_proxyclient_address: "%{hiera('internal_api_edge1')}"
    neutron::agents::ml2::ovs::local_ip: "%{hiera('tenant_edge1')}"
    cold_migration_ssh_inbound_addr: "%{hiera('internal_api_edge1')}"
    live_migration_ssh_inbound_addr: "%{hiera('internal_api_edge1')}"
    nova::migration::libvirt::live_migration_inbound_addr: "%{hiera('internal_api_edge1')}"
    nova::my_ip: "%{hiera('internal_api_edge1')}"
    tripleo::profile::base::database::mysql::client::mysql_client_bind_address: "%{hiera('internal_api_edge1')}"

  ComputeEdge1vduImage: "overcloud-realtime-compute"
  ComputeEdge1vduParameters:
    KernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=128 intel_iommu=on iommu=pt"
    IsolCpusList: 2-35,38-71
    NovaVcpuPinSet: 2-35,38-71

  ComputeEdge1vduExtraConfig:
    nova::compute::libvirt::vncserver_listen: "%{hiera('internal_api_edge1')}"
    nova::compute::vncserver_proxyclient_address: "%{hiera('internal_api_edge1')}"
    neutron::agents::ml2::ovs::local_ip: "%{hiera('tenant_edge1')}"
    cold_migration_ssh_inbound_addr: "%{hiera('internal_api_edge1')}"
    live_migration_ssh_inbound_addr: "%{hiera('internal_api_edge1')}"
    nova::migration::libvirt::live_migration_inbound_addr: "%{hiera('internal_api_edge1')}"
    nova::my_ip: "%{hiera('internal_api_edge1')}"
    tripleo::profile::base::database::mysql::client::mysql_client_bind_address: "%{hiera('internal_api_edge1')}"

  ComputeEdge2vduImage: "overcloud-realtime-compute"
  ComputeEdge2Parameters:
    KernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=128 intel_iommu=on iommu=pt"
    IsolCpusList: 2-35,38-71
    NovaVcpuPinSet: 2-35,38-71

  ComputeEdge2ExtraConfig:
    nova::compute::libvirt::vncserver_listen: "%{hiera('internal_api_edge2')}"
    nova::compute::vncserver_proxyclient_address: "%{hiera('internal_api_edge2')}"
    neutron::agents::ml2::ovs::local_ip: "%{hiera('tenant_edge2')}"
    cold_migration_ssh_inbound_addr: "%{hiera('internal_api_edge2')}"
    live_migration_ssh_inbound_addr: "%{hiera('internal_api_edge2')}"
    nova::migration::libvirt::live_migration_inbound_addr: "%{hiera('internal_api_edge2')}"
    nova::my_ip: "%{hiera('internal_api_edge2')}"
    tripleo::profile::base::database::mysql::client::mysql_client_bind_address: "%{hiera('internal_api_edge2')}"

  ComputeEdge2vduParameters:
    KernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=128 intel_iommu=on iommu=pt"
    IsolCpusList: 2-35,38-71
    NovaVcpuPinSet: 2-35,38-71

  ComputeEdge2vduExtraConfig:
    nova::compute::libvirt::vncserver_listen: "%{hiera('internal_api_edge2')}"
    nova::compute::vncserver_proxyclient_address: "%{hiera('internal_api_edge2')}"
    neutron::agents::ml2::ovs::local_ip: "%{hiera('tenant_edge2')}"
    cold_migration_ssh_inbound_addr: "%{hiera('internal_api_edge2')}"
    live_migration_ssh_inbound_addr: "%{hiera('internal_api_edge2')}"
    nova::migration::libvirt::live_migration_inbound_addr: "%{hiera('internal_api_edge2')}"
    nova::my_ip: "%{hiera('internal_api_edge2')}"
    tripleo::profile::base::database::mysql::client::mysql_client_bind_address: "%{hiera('internal_api_edge2')}"
