resource_registry:
# Configure Networks
  OS::TripleO::Controller::Net::SoftwareConfig:
    ../network/config/multiple-nics/controller.yaml
  OS::TripleO::Compute::Net::SoftwareConfig:
    ../network/config/single-nic-vlans/compute.yaml
  OS::TripleO::ComputeHCI::Net::SoftwareConfig:
    ../network/config/single-nic-vlans/compute-hci.yaml
  OS::TripleO::ComputeEdge1::Net::SoftwareConfig:
    ../network/config/single-nic-vlans/compute-e1.yaml
  OS::TripleO::ComputeEdge1vdu::Net::SoftwareConfig:
    ../network/config/single-nic-vlans/compute-e1vdu.yaml
  OS::TripleO::ComputeEdge2::Net::SoftwareConfig:
    ../network/config/single-nic-vlans/compute-e2.yaml
  OS::TripleO::ComputeEdge2vdu::Net::SoftwareConfig:
    ../network/config/single-nic-vlans/compute-e2vdu.yaml

parameter_defaults:
  DnsServers:
  - 172.17.118.8
  NtpServer:
  - 172.17.118.1
  - 172.17.118.3
  - 172.17.118.5

  BondInterfaceOvsOptions: "mode=4 miimon=100"

  DockerInsecureRegistryAddress:
  - 172.17.118.8:5000
  - satellite.lab.roskosb.info:5000

  ControllerControlPlaneSubnet: leaf0
  ComputeControlPlaneSubnet: leaf0
  ComputeHCIControlPlaneSubnet: leaf0
  ComputeEdge1ControlPlaneSubnet: edge1
  ComputeEdge1vduControlPlaneSubnet: edge1
  ComputeEdge2ControlPlaneSubnet: edge2
  ComputeEdge2vduControlPlaneSubnet: edge2

#  ControlPlaneSubnetCidr: '26'
#  ControlPlaneSubnet: leaf0
#  ControlPlaneDefaultRoute: 192.168.120.62

  NeutronNetworkType: 'vxlan,vlan'
  NeutronTunnelTypes: ''
  NeutronNetworkVLANRanges:
    - management:117:117
    - sriov-1:200:300
    - sriov-2:200:300
    - fronthaul-1:200:300
    - fronthaul-2:200:300
  NeutronFlatNetworks:
    - floating-ips

  NeutronBridgeMappings:
    - tenant:br-tenant
    - datacentre:br-ex
    - management:br-mgmt
    - floating-ips:br-float

  CloudName: overcloud.lab.roskosb.info
  CloudDomain: lab.roskosb.info

  NeutronEnableIsolatedMetadata: true
  NeutronEnableForceMetadata: true
  NeutronEnableMetadataNetwork: true
#  NeutronGlobalPhysnetMtu: 9000

  NovaReservedHostMemory: 4096
  OvercloudControllerFlavor: control
  OvercloudComputeFlavor: compute
  OvercloudComputeHCIFlavor: compute-hci
  OvercloudComputeEdge1Flavor: compute-edge1
  OvercloudComputeEdge1vduFlavor: compute-edge1vdu
  OvercloudComputeEdge2Flavor: compute-edge2
  OvercloudComputeEdge2vduFlavor: compute-edge2vdu
  ControllerCount: 3
  ComputeCount: 2
  ComputeHCICount: 3
  ComputeEdge1Count: 1
  ComputeEdge1vduCount: 1
  ComputeEdge2Count: 1
  ComputeEdge2vduCount: 1

  NovaSchedulerDefaultFilters:
    - RetryFilter
    - AvailabilityZoneFilter
    - AggregateRamFilter
    - AggregateCoreFilter
    - ComputeFilter
    - AggregateInstanceExtraSpecsFilter
    - ComputeCapabilitiesFilter
    - ImagePropertiesFilter
    - ServerGroupAntiAffinityFilter
    - ServerGroupAffinityFilter
    - PciPassthroughFilter
    - RamFilter
    - DiskFilter
    - NUMATopologyFilter

  PublicVirtualFixedIPs: [{'ip_address':'172.17.119.10'}]

  ControllerExtraConfig:
    nova::cpu_allocation_ratio: 1
    nova::pci::aliases:
      - name: vc_fpga
        vendor_id: '1172'
        product_id: '5050'
        device_type: 'type-VF'

  ComputeParameters:
    KernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=128 intel_iommu=on iommu=pt"
    IsolCpusList: 2-35,38-71
    NovaVcpuPinSet: 2-35,38-71
    NovaComputeCpuSharedSet: 0,1,36,37
    NeutronPhysicalDevMappings:
      - sriov-1:p3p1
      - sriov-2:p3p2
      - sriov-1:p7p1
      - sriov-2:p7p2
    NeutronSriovNumVFs:
      - p3p1:8
      - p3p2:8
      - p7p1:8
      - p7p2:8
    NovaPCIPassthrough:
      - devname: "p3p1"
        physical_network: "sriov-1"
      - devname: "p3p2"
        physical_network: "sriov-2"
      - devname: "p7p1"
        physical_network: "sriov-1"
      - devname: "p7p2"
        physical_network: "sriov-2"

  ComputeExtraConfig:
    nova::cpu_allocation_ratio: 1
    nova::compute::resume_guests_state_on_host_boot: true

#  ComputeHCIImage: "overcloud-full-hci"
  ComputeHCIParameters:
    KernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=128 intel_iommu=on iommu=pt"
    IsolCpusList: 2-35,38-71
    NovaVcpuPinSet: 6-35,42-71
    NovaComputeCpuSharedSet: 0,1,36,37
    NovaReservedHostMemory: 30720
    NeutronPhysicalDevMappings:
      - sriov-1:p3p1
      - sriov-2:p3p2
      - sriov-1:p7p1
      - sriov-2:p7p2
    NeutronSriovNumVFs:
      - p3p1:8
      - p3p2:8
      - p7p1:8
      - p7p2:8
    NovaPCIPassthrough:
      - devname: "p3p1"
        physical_network: "sriov-1"
      - devname: "p3p2"
        physical_network: "sriov-2"
      - devname: "p7p1"
        physical_network: "sriov-1"
      - devname: "p7p2"
        physical_network: "sriov-2"

  ComputeHCIExtraConfig:
    nova::cpu_allocation_ratio: 1
    nova::compute::resume_guests_state_on_host_boot: true

  ComputeEdge1Parameters:
    KernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=128 intel_iommu=on iommu=pt"
    IsolCpusList: 2-35,38-71
    NovaVcpuPinSet: 2-35,38-71
    NovaComputeCpuSharedSet: 0,1,36,37
    NovaEnableRbdBackend: false
    NeutronPhysicalDevMappings:
      - sriov-1:p3p1
      - sriov-2:p3p2
      - sriov-1:p7p1
      - sriov-2:p7p2
    NeutronSriovNumVFs:
      - p3p1:8
      - p3p2:8
      - p7p1:8
      - p7p2:8
    NovaPCIPassthrough:
      - devname: "p3p1"
        physical_network: "sriov-1"
      - devname: "p3p2"
        physical_network: "sriov-2"
      - devname: "p7p1"
        physical_network: "sriov-1"
      - devname: "p7p2"
        physical_network: "sriov-2"

  ComputeEdge1ExtraConfig:
    nova::compute::libvirt::vncserver_listen: "%{hiera('internal_api_edge1')}"
    nova::compute::vncserver_proxyclient_address: "%{hiera('internal_api_edge1')}"
    neutron::agents::ml2::ovs::local_ip: "%{hiera('tenant_edge1')}"
    cold_migration_ssh_inbound_addr: "%{hiera('internal_api_edge1')}"
    live_migration_ssh_inbound_addr: "%{hiera('internal_api_edge1')}"
    nova::migration::libvirt::live_migration_inbound_addr: "%{hiera('internal_api_edge1')}"
    nova::my_ip: "%{hiera('internal_api_edge1')}"
    tripleo::profile::base::database::mysql::client::mysql_client_bind_address: "%{hiera('internal_api_edge1')}"
    nova::cpu_allocation_ratio: 1
    nova::compute::resume_guests_state_on_host_boot: true
    nova::compute::libvirt::libvirt_cpu_model: host-passthrough
    nova::compute::libvirt::libvirt_cpu_model_extra_flags: host-tsc-deadline
    nova::compute::libvirt::mem_stats_period_seconds: 0

  ComputeEdge1vduImage: "overcloud-realtime-compute"
  ComputeEdge1vduParameters:
    KernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=128 nx_huge_pages_recovery_ratio=0 intel_iommu=on iommu=pt elevator=cfq audit=1 nomodeset intel_idle.max_cstate=1 tsc=reliable idle=poll rcu_nocb_poll=1 clocksource=tsc pcie_aspm.policy=performance"
    IsolCpusList: 2-35,38-71
    NovaVcpuPinSet: 2-35,38-71
    NovaComputeCpuSharedSet: 0,1,36,37
    NovaEnableRbdBackend: false
    NeutronPhysicalDevMappings:
      - fronthaul-1:p1p1
      - fronthaul-2:p1p2
      - fronthaul-1:p4p1
      - fronthaul-2:p4p2
      - sriov-1:p3p1
      - sriov-2:p3p2
      - sriov-1:p8p1
      - sriov-2:p8p2
    NeutronSriovNumVFs:
      - p3p1:8
      - p3p2:8
      - p8p1:8
      - p8p2:8    
      - p1p1:8
      - p1p2:8
      - p4p1:8
      - p4p2:8
    NovaPCIPassthrough:
      - devname: "p1p1"
        physical_network: "fronthaul-1"
      - devname: "p1p2"
        physical_network: "fronthaul-2"
      - devname: "p4p1"
        physical_network: "fronthaul-1"
      - devname: "p4p2"
        physical_network: "fronthaul-2"
      - devname: "p3p1"
        physical_network: "sriov-1"
      - devname: "p3p2"
        physical_network: "sriov-2"
      - devname: "p8p1"
        physical_network: "sriov-1"
      - devname: "p8p2"
        physical_network: "sriov-2"
      - vendor_id: "1172"
        product_id: "5050"

  ComputeEdge1vduExtraConfig:
    nova::compute::libvirt::vncserver_listen: "%{hiera('internal_api_edge1')}"
    nova::compute::vncserver_proxyclient_address: "%{hiera('internal_api_edge1')}"
    neutron::agents::ml2::ovs::local_ip: "%{hiera('tenant_edge1')}"
    cold_migration_ssh_inbound_addr: "%{hiera('internal_api_edge1')}"
    live_migration_ssh_inbound_addr: "%{hiera('internal_api_edge1')}"
    nova::migration::libvirt::live_migration_inbound_addr: "%{hiera('internal_api_edge1')}"
    nova::my_ip: "%{hiera('internal_api_edge1')}"
    tripleo::profile::base::database::mysql::client::mysql_client_bind_address: "%{hiera('internal_api_edge1')}"
    nova::cpu_allocation_ratio: 1
    nova::compute::resume_guests_state_on_host_boot: true
    nova::pci::aliases:
      - name: vc_fpga
        vendor_id: '1172'
        product_id: '5050'
        device_type: 'type-VF'

  ComputeEdge2Parameters:
    KernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=128 intel_iommu=on iommu=pt"
    IsolCpusList: 2-35,38-71
    NovaVcpuPinSet: 2-35,38-71
    NovaComputeCpuSharedSet: 0,1,36,37
    NovaEnableRbdBackend: false
    NeutronPhysicalDevMappings:
      - sriov-1:p3p1
      - sriov-2:p3p2
      - sriov-1:p7p1
      - sriov-2:p7p2
    NeutronSriovNumVFs:
      - p3p1:8
      - p3p2:8
      - p7p1:8
      - p7p2:8
    NovaPCIPassthrough:
      - devname: "p3p1"
        physical_network: "sriov-1"
      - devname: "p3p2"
        physical_network: "sriov-2"
      - devname: "p7p1"
        physical_network: "sriov-1"
      - devname: "p7p2"
        physical_network: "sriov-2"

  ComputeEdge2ExtraConfig:
    nova::compute::libvirt::vncserver_listen: "%{hiera('internal_api_edge2')}"
    nova::compute::vncserver_proxyclient_address: "%{hiera('internal_api_edge2')}"
    neutron::agents::ml2::ovs::local_ip: "%{hiera('tenant_edge2')}"
    cold_migration_ssh_inbound_addr: "%{hiera('internal_api_edge2')}"
    live_migration_ssh_inbound_addr: "%{hiera('internal_api_edge2')}"
    nova::migration::libvirt::live_migration_inbound_addr: "%{hiera('internal_api_edge2')}"
    nova::my_ip: "%{hiera('internal_api_edge2')}"
    tripleo::profile::base::database::mysql::client::mysql_client_bind_address: "%{hiera('internal_api_edge2')}"
    nova::cpu_allocation_ratio: 1
    nova::compute::resume_guests_state_on_host_boot: true
    nova::compute::libvirt::libvirt_cpu_model: host-passthrough
    nova::compute::libvirt::libvirt_cpu_model_extra_flags: host-tsc-deadline
    nova::compute::libvirt::mem_stats_period_seconds: 0

  ComputeEdge2vduImage: "overcloud-realtime-compute"
  ComputeEdge2vduParameters:
    KernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=128 nx_huge_pages_recovery_ratio=0 intel_iommu=on iommu=pt elevator=cfq audit=1 nomodeset intel_idle.max_cstate=1 tsc=reliable idle=poll rcu_nocb_poll=1 clocksource=tsc pcie_aspm.policy=performance"
    IsolCpusList: 2-35,38-71
    NovaVcpuPinSet: 2-35,38-71
    NovaComputeCpuSharedSet: 0,1,36,37
    NovaEnableRbdBackend: false
    NeutronPhysicalDevMappings:
      - fronthaul-1:p1p1
      - fronthaul-2:p1p2
      - fronthaul-1:p4p1
      - fronthaul-2:p4p2
      - sriov-1:p3p1
      - sriov-2:p3p2
      - sriov-1:p8p1
      - sriov-2:p8p2
    NeutronSriovNumVFs:
      - p3p1:8
      - p3p2:8
      - p8p1:8
      - p8p2:8
      - p1p1:8
      - p1p2:8
      - p4p1:8
      - p4p2:8
    NovaPCIPassthrough:
      - devname: "p1p1"
        physical_network: "fronthaul-1"
      - devname: "p1p2"
        physical_network: "fronthaul-2"
      - devname: "p4p1"
        physical_network: "fronthaul-1"
      - devname: "p4p2"
        physical_network: "fronthaul-2"
      - devname: "p3p1"
        physical_network: "sriov-1"
      - devname: "p3p2"
        physical_network: "sriov-2"
      - devname: "p8p1"
        physical_network: "sriov-1"
      - devname: "p8p2"
        physical_network: "sriov-2"
      - vendor_id: "1172"
        product_id: "5050"

  ComputeEdge2vduExtraConfig:
    nova::compute::libvirt::vncserver_listen: "%{hiera('internal_api_edge2')}"
    nova::compute::vncserver_proxyclient_address: "%{hiera('internal_api_edge2')}"
    neutron::agents::ml2::ovs::local_ip: "%{hiera('tenant_edge2')}"
    cold_migration_ssh_inbound_addr: "%{hiera('internal_api_edge2')}"
    live_migration_ssh_inbound_addr: "%{hiera('internal_api_edge2')}"
    nova::migration::libvirt::live_migration_inbound_addr: "%{hiera('internal_api_edge2')}"
    nova::my_ip: "%{hiera('internal_api_edge2')}"
    tripleo::profile::base::database::mysql::client::mysql_client_bind_address: "%{hiera('internal_api_edge2')}"
    nova::cpu_allocation_ratio: 1
    nova::compute::resume_guests_state_on_host_boot: true
    nova::pci::aliases:
      - name: vc_fpga
        vendor_id: '1172'
        product_id: '5050'
        device_type: 'type-VF'

  RhsmVars:
    rhsm_method: "satellite"
    rhsm_server_hostname: "satellite.lab.roskosb.info"
    rhsm_baseurl: "https://satellite.lab.roskosb.info/pulp/repos"
    rhsm_activation_key: "osp16-dev"
    rhsm_org_id: "lab"
    rhsm_force_register: True
