resource_registry:
# Configure Networks
  OS::TripleO::Controller::Net::SoftwareConfig:
    ../network/config/multiple-nics/controller.yaml
  OS::TripleO::Compute::Net::SoftwareConfig:
    ../network/config/single-nic-vlans/compute.yaml
  OS::TripleO::ComputeHCI::Net::SoftwareConfig:
    ../network/config/single-nic-vlans/compute-hci.yaml
  OS::TripleO::ComputeEdge1::Net::SoftwareConfig:
    ../network/config/single-nic-vlans/compute-e1.yaml
  OS::TripleO::ComputeEdge1vdu::Net::SoftwareConfig:
    ../network/config/single-nic-vlans/compute-e1.yaml
  OS::TripleO::ComputeEdge2::Net::SoftwareConfig:
    ../network/config/single-nic-vlans/compute-e2.yaml
  OS::TripleO::ComputeEdge2vdu::Net::SoftwareConfig:
    ../network/config/single-nic-vlans/compute-e2.yaml

parameter_defaults:
  DnsServers:
  - 172.17.118.8
  NtpServer:
  - 172.17.118.1
  - 172.17.118.3
  - 172.17.118.5
  EC2MetadataIp: 192.168.120.5
  NeutronExternalNetworkBridge: "''"
  BondInterfaceOvsOptions: "mode=4 miimon=100"
  DockerInsecureRegistryAddress:
  - 172.17.118.8:5000
  - satellite.lab.roskosb.info:5000

  ControllerControlPlaneSubnet: leaf0
  ComputeControlPlaneSubnet: leaf0
  ComputeHCIControlPlaneSubnet: leaf0
  ComputeEdge1ControlPlaneSubnet: edge1
  ComputeEdge1vduControlPlaneSubnet: edge1
  ComputeEdge2ControlPlaneSubnet: edge2
  ComputeEdge2vduControlPlaneSubnet: edge2

  ControlPlaneSubnetCidr: '26'
  ControlPlaneSubnet: leaf0
  ControlPlaneDefaultRoute: 192.168.120.62
  ControlPlaneEdge1DefaultRoute: 192.168.120.126
  ControlPlaneEdge1SubnetCidr: '26'
  ControlPlaneEdge2DefaultRoute: 192.168.120.190
  ControlPlaneEdge2SubnetCidr: '26'

  NeutronNetworkType: 'vxlan,vlan'
  NeutronNetworkVLANRanges:
    - management:117:117
    - tenant:300:400
    - backhaul:202:202
    - midhaul:204:205
    - fronthaul:203:203

  NeutronTunnelTypes: ''

  NeutronBridgeMappings:
  - tenant:br-tenant
  - datacentre:br-ex
  - management:br-mgmt
  - floating-ips:br-float

  InternalApiSupernet: 192.168.130.0/24
  TenantSupernet: 192.168.201.0/24
  ControlPlaneSupernet: 192.168.120.0/24

  CloudName: overcloud.lab.roskosb.info
  CloudDomain: lab.roskosb.info

  NeutronEnableIsolatedMetadata: true
  NeutronEnableForceMetadata: true
  NeutronEnableMetadataNetwork: true
#  NeutronGlobalPhysnetMtu: 9000

  NovaReservedHostMemory: 4096
  OvercloudControllerFlavor: control
  OvercloudComputeFlavor: compute
  OvercloudComputeHCIFlavor: compute-hci
  OvercloudComputeEdge1Flavor: compute-edge1
  OvercloudComputeEdge1vduFlavor: compute-edge1vdu
  OvercloudComputeEdge2Flavor: compute-edge2
  OvercloudComputeEdge2vduFlavor: compute-edge2vdu
  ControllerCount: 3
  ComputeCount: 1
  ComputeHCICount: 3
  ComputeEdge1Count: 1
  ComputeEdge1vduCount: 1
  ComputeEdge2Count: 1
  ComputeEdge2vduCount: 1

  NovaSchedulerDefaultFilters:
    - RetryFilter
    - AvailabilityZoneFilter
    - AggregateRamFilter
    - AggregateCoreFilter
    - ComputeFilter
    - AggregateInstanceExtraSpecsFilter
    - ComputeCapabilitiesFilter
    - ImagePropertiesFilter
    - ServerGroupAntiAffinityFilter
    - ServerGroupAffinityFilter
    - PciPassthroughFilter
    - RamFilter
    - DiskFilter
    - NUMATopologyFilter

  PublicVirtualFixedIPs: [{'ip_address':'172.17.119.10'}]

  ControllerExtraConfig:
    nova::pci::aliases:
      - name: vc_fpga
        vendor_id: '1172'
        product_id: '5050'
        device_type: 'type-VF'

  ComputeParameters:
    KernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=128 intel_iommu=on iommu=pt"
    IsolCpusList: 2-35,38-71
    NovaVcpuPinSet: 2-35,38-71
    NeutronPhysicalDevMappings:
      - backhaul:p3p1
      - backhaul:p3p2
      - midhaul:p7p1
      - midhaul:p7p2
    NeutronSriovNumVFs:
      - p3p1:8
      - p3p2:8
      - p7p1:8
      - p7p2:8
    NovaPCIPassthrough:
      - devname: "p3p1"
        physical_network: "backhaul"
      - devname: "p3p2"
        physical_network: "backhaul"
      - devname: "p7p1"
        physical_network: "midhaul"
      - devname: "p7p2"
        physical_network: "midhaul"

#  ComputeHCIImage: "overcloud-full-hci"
  ComputeHCIParameters:
    KernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=128 intel_iommu=on iommu=pt"
    IsolCpusList: 2-35,38-71
    NovaVcpuPinSet: 6-35,42-71
    NovaReservedHostMemory: 30720
    NeutronPhysicalDevMappings:
      - backhaul:p3p1
      - backhaul:p3p2
      - midhaul:p7p1
      - midhaul:p7p2
    NeutronSriovNumVFs:
      - p3p1:8
      - p3p2:8
      - p7p1:8
      - p7p2:8
    NovaPCIPassthrough:
      - devname: "p3p1"
        physical_network: "backhaul"
      - devname: "p3p2"
        physical_network: "backhaul"
      - devname: "p7p1"
        physical_network: "midhaul"
      - devname: "p7p2"
        physical_network: "midhaul"

  ComputeHCIExtraConfig:
    nova::cpu_allocation_ratio: 1

  ComputeEdge1Parameters:
    KernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=128 intel_iommu=on iommu=pt"
    IsolCpusList: 2-35,38-71
    NovaVcpuPinSet: 2-35,38-71
    NovaEnableRbdBackend: false
    NeutronPhysicalDevMappings:
      - backhaul:p3p1
      - backhaul:p3p2
      - midhaul:p7p1
      - midhaul:p7p2
    NeutronSriovNumVFs:
      - p3p1:8
      - p3p2:8
      - p7p1:8
      - p7p2:8
    NovaPCIPassthrough:
      - devname: "p3p1"
        physical_network: "backhaul"
      - devname: "p3p2"
        physical_network: "backhaul"
      - devname: "p7p1"
        physical_network: "midhaul"
      - devname: "p7p2"
        physical_network: "midhaul"

  ComputeEdge1ExtraConfig:
    nova::compute::libvirt::vncserver_listen: "%{hiera('internal_api_edge1')}"
    nova::compute::vncserver_proxyclient_address: "%{hiera('internal_api_edge1')}"
    neutron::agents::ml2::ovs::local_ip: "%{hiera('tenant_edge1')}"
    cold_migration_ssh_inbound_addr: "%{hiera('internal_api_edge1')}"
    live_migration_ssh_inbound_addr: "%{hiera('internal_api_edge1')}"
    nova::migration::libvirt::live_migration_inbound_addr: "%{hiera('internal_api_edge1')}"
    nova::my_ip: "%{hiera('internal_api_edge1')}"
    tripleo::profile::base::database::mysql::client::mysql_client_bind_address: "%{hiera('internal_api_edge1')}"

  ComputeEdge1vduImage: "overcloud-realtime-compute"
  ComputeEdge1vduParameters:
    KernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=128 intel_iommu=on iommu=pt"
    IsolCpusList: 2-35,38-71
    NovaVcpuPinSet: 2-35,38-71
    NovaEnableRbdBackend: false
    NeutronPhysicalDevMappings:
      - fronthaul:p4p1
      - fronthaul:p5p1
      - midhaul:p8p1
      - midhaul:p8p2
    NeutronSriovNumVFs:
      - p7p1:8
      - p7p2:8
      - p8p1:8
      - p8p2:8    
      - p4p1:8
      - p5p1:8
    NovaPCIPassthrough:
      - devname: "p4p1"
        physical_network: "fronthaul"
      - devname: "p5p1"
        physical_network: "fronthaul"
      - devname: "p8p1"
        physical_network: "midhaul"
      - devname: "p8p2"
        physical_network: "midhaul"
      - vendor_id: "1172"
        product_id: "5050"

  ComputeEdge1vduExtraConfig:
    nova::compute::libvirt::vncserver_listen: "%{hiera('internal_api_edge1')}"
    nova::compute::vncserver_proxyclient_address: "%{hiera('internal_api_edge1')}"
    neutron::agents::ml2::ovs::local_ip: "%{hiera('tenant_edge1')}"
    cold_migration_ssh_inbound_addr: "%{hiera('internal_api_edge1')}"
    live_migration_ssh_inbound_addr: "%{hiera('internal_api_edge1')}"
    nova::migration::libvirt::live_migration_inbound_addr: "%{hiera('internal_api_edge1')}"
    nova::my_ip: "%{hiera('internal_api_edge1')}"
    tripleo::profile::base::database::mysql::client::mysql_client_bind_address: "%{hiera('internal_api_edge1')}"
    nova::pci::aliases:
      - name: vc_fpga
        vendor_id: '1172'
        product_id: '5050'
        device_type: 'type-VF'

  ComputeEdge2Parameters:
    KernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=128 intel_iommu=on iommu=pt"
    IsolCpusList: 2-35,38-71
    NovaVcpuPinSet: 2-35,38-71
    NovaEnableRbdBackend: false
    NovaPCIPassthrough:
      - devname: "p3p1"
        physical_network: "backhaul"
      - devname: "p3p2"
        physical_network: "backhaul"
      - devname: "p7p1"
        physical_network: "midhaul"
      - devname: "p7p2"
        physical_network: "midhaul"

  ComputeEdge2ExtraConfig:
    nova::compute::libvirt::vncserver_listen: "%{hiera('internal_api_edge2')}"
    nova::compute::vncserver_proxyclient_address: "%{hiera('internal_api_edge2')}"
    neutron::agents::ml2::ovs::local_ip: "%{hiera('tenant_edge2')}"
    cold_migration_ssh_inbound_addr: "%{hiera('internal_api_edge2')}"
    live_migration_ssh_inbound_addr: "%{hiera('internal_api_edge2')}"
    nova::migration::libvirt::live_migration_inbound_addr: "%{hiera('internal_api_edge2')}"
    nova::my_ip: "%{hiera('internal_api_edge2')}"
    tripleo::profile::base::database::mysql::client::mysql_client_bind_address: "%{hiera('internal_api_edge2')}"

  ComputeEdge2vduImage: "overcloud-realtime-compute78"
  ComputeEdge2vduParameters:
    KernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=128 intel_iommu=on iommu=pt"
    IsolCpusList: 2-35,38-71
    NovaVcpuPinSet: 2-35,38-71
    NovaEnableRbdBackend: false
    NeutronPhysicalDevMappings:
      - fronthaul:p4p1
      - fronthaul:p5p1
      - midhaul:p8p1
      - midhaul:p8p2
    NeutronSriovNumVFs:
      - p7p1:8
      - p7p2:8
      - p8p1:8
      - p8p2:8
      - p4p1:8
      - p5p1:8
    NovaPCIPassthrough:
      - devname: "p4p1"
        physical_network: "fronthaul"
      - devname: "p5p1"
        physical_network: "fronthaul"
      - devname: "p8p1"
        physical_network: "midhaul"
      - devname: "p8p2"
        physical_network: "midhaul"
      - vendor_id: "1172"
        product_id: "5050"

  ComputeEdge2vduExtraConfig:
    nova::compute::libvirt::vncserver_listen: "%{hiera('internal_api_edge2')}"
    nova::compute::vncserver_proxyclient_address: "%{hiera('internal_api_edge2')}"
    neutron::agents::ml2::ovs::local_ip: "%{hiera('tenant_edge2')}"
    cold_migration_ssh_inbound_addr: "%{hiera('internal_api_edge2')}"
    live_migration_ssh_inbound_addr: "%{hiera('internal_api_edge2')}"
    nova::migration::libvirt::live_migration_inbound_addr: "%{hiera('internal_api_edge2')}"
    nova::my_ip: "%{hiera('internal_api_edge2')}"
    tripleo::profile::base::database::mysql::client::mysql_client_bind_address: "%{hiera('internal_api_edge2')}"
    nova::pci::aliases:
      - name: vc_fpga
        vendor_id: '1172'
        product_id: '5050'
        device_type: 'type-VF'