resource_registry:
# Configure Networks
  OS::TripleO::Controller::Net::SoftwareConfig: ../network/config/multiple-nics/controller.yaml
  OS::TripleO::Compute::Net::SoftwareConfig: ../network/config/single-nic-vlans/compute.yaml
  OS::TripleO::ComputeEdge1::Net::SoftwareConfig: ../network/config/single-nic-vlans/compute-e1.yaml
  OS::TripleO::ComputeEdge1vdu::Net::SoftwareConfig: ../network/config/single-nic-vlans/compute-e1.yaml
  OS::TripleO::ComputeEdge2::Net::SoftwareConfig: ../network/config/single-nic-vlans/compute-e2.yaml
  OS::TripleO::ComputeEdge2vdu::Net::SoftwareConfig: ../network/config/single-nic-vlans/compute-e2.yaml

# Disable Cinder
  OS::TripleO::Services::CinderApi: OS::Heat::None
  OS::TripleO::Services::CinderBackup: OS::Heat::None
  OS::TripleO::Services::CinderScheduler: OS::Heat::None
  OS::TripleO::Services::CinderVolume: OS::Heat::None

parameter_defaults:
  DnsServers: ["192.168.120.5"]
  #NtpServer: ["35.135.192.20", "35.135.192.21"]
  EC2MetadataIp: 192.168.120.5
  NeutronExternalNetworkBridge: "''"
  BondInterfaceOvsOptions: "mode=4 miimon=100"
#  DockerInsecureRegistryAddress:
#  - 44.154.16.11:5000
#  - satellite-eng.nfv.charterlab.com:5000

  ControllerControlPlaneSubnet: leaf0
  ComputeControlPlaneSubnet: leaf0
  ComputeEdge1ControlPlaneSubnet: edge1
  ComputeEdge1vduControlPlaneSubnet: edge1
  ComputeEdge2ControlPlaneSubnet: edge2
  ComputeEdge2vduControlPlaneSubnet: edge2

  ControlPlaneSubnetCidr: '26'
  ControlPlaneSubnet: leaf0
  ControlPlaneDefaultRoute: 192.168.120.62
  ControlPlaneEdge1DefaultRoute: 192.168.120.126
  ControlPlaneEdge1SubnetCidr: '26'
  ControlPlaneEdge2DefaultRoute: 192.168.120.190
  ControlPlaneEdge2SubnetCidr: '26'

  NeutronBridgeMappings:
  - tenant:br-tenant
  - datacentre:br-ex

#  NeutronNetworkVLANRanges:
#    - tenant:1000:2000
#    - provider:1000:2000
#    - leaf2:1000:1000
#    - edge1:1000:1000

  InternalApiSupernet: 192.168.130.0/24
  TenantSupernet: 192.168.201.0/24

  CloudName: overcloud.lab.roskosb.info
  CloudDomain: lab.roskosb.info

  NeutronEnableIsolatedMetadata: true
  NeutronEnableForceMetadata: true
  NeutronEnableMetadataNetwork: true
  NeutronGlobalPhysnetMtu: 9000

  NovaReservedHostMemory: 1024
  OvercloudControllerFlavor: control
  OvercloudComputeFlavor: compute
  OvercloudComputeEdge1Flavor: compute-edge1
  OvercloudComputeEdge1vduFlavor: compute-edge1vdu
  OvercloudComputeEdge2Flavor: compute-edge2
  OvercloudComputeEdge2vduFlavor: compute-edge2vdu
  ControllerCount: 3
  ComputeCount: 3
  ComputeEdge1Count: 1
  ComputeEdge1vduCount: 1
  ComputeEdge2Count: 1
  ComputeEdge2vduCount: 1

  NovaSchedulerDefaultFilters:
    - RetryFilter
    - AvailabilityZoneFilter
    - AggregateRamFilter
    - AggregateCoreFilter
    - ComputeFilter
    - AggregateInstanceExtraSpecsFilter
    - ComputeCapabilitiesFilter
    - ImagePropertiesFilter
    - ServerGroupAntiAffinityFilter
    - ServerGroupAffinityFilter
    - RamFilter
    - DiskFilter

  PublicVirtualFixedIPs: [{'ip_address':'172.17.119.10'}]

  SwiftRawDisks:
    sdb: {}

