resource_registry:
# Configure Networks
  OS::TripleO::Controller::Net::SoftwareConfig:
    ../network/config/multiple-nics/controller.yaml
  OS::TripleO::ComputeSriov::Net::SoftwareConfig:
    ../network/config/bond-with-vlans/computeSriov.yaml

# Disable Swift
  OS::TripleO::Services::SwiftProxy: OS::Heat::None
  OS::TripleO::Services::SwiftStorage: OS::Heat::None
  OS::TripleO::Services::SwiftRingBuilder: OS::Heat::None

parameter_defaults:

  NovaComputeAvailabilityZone: central
  RootStackName: central

  NeutronBridgeMappings:
    - tenant:br-tenant
    - datacentre:br-ex
    - ovs-central:br-provider
    - floating-ips:br-float

  ControllerControlPlaneSubnet: ctlplane-subnet
  ComputeSriovControlPlaneSubnet: ctlplane-subnet
  VipSubnetMap:
    ctlplane: ctlplane-subnet
  OvercloudControllerFlavor: control
  OvercloudComputeSriovFlavor: computeSriov
  ControllerCount: 3
  ComputeSriovCount: 1

  NovaSchedulerDefaultFilters:
    - RetryFilter
    - AvailabilityZoneFilter
    - ComputeFilter
    - AggregateInstanceExtraSpecsFilter
    - ComputeCapabilitiesFilter
    - ImagePropertiesFilter
    - ServerGroupAntiAffinityFilter
    - ServerGroupAffinityFilter
    - PciPassthroughFilter
    - NUMATopologyFilter

  PublicVirtualFixedIPs: [{'ip_address':'172.17.119.10'}]

  ControllerExtraConfig:
    nova::cpu_allocation_ratio: 1
    nova::pci::aliases:
      - name: vc_fpga
        vendor_id: '1172'
        product_id: '5050'
        device_type: 'type-VF'

  ComputeSriovParameters:
    KernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=128 intel_iommu=on iommu=pt"
    IsolCpusList: 2-35,38-71
    NovaComputeCpuDedicatedSet: 2-35,38-71
    NovaComputeCpuSharedSet: 0,1,36,37
    NeutronPhysicalDevMappings:
      - sriov1-central:ens3f0
      - sriov2-central:ens3f1
      - sriov1-central:ens7f0
      - sriov2-central:ens7f1
    NeutronSriovNumVFs:
      - ens3f0:8
      - ens3f1:8
      - ens7f0:8
      - ens7f1:8
    NovaPCIPassthrough:
      - devname: "ens3f0"
        physical_network: "sriov1-central"
      - devname: "ens3f1"
        physical_network: "sriov2-central"
      - devname: "ens7f0"
        physical_network: "sriov1-central"
      - devname: "ens7f1"
        physical_network: "sriov2-central"

  ComputeSriovExtraConfig:
    nova::cpu_allocation_ratio: 1
    nova::compute::resume_guests_state_on_host_boot: true
