resource_registry:
# Configure Networks

  OS::TripleO::ComputeEdge1::Net::SoftwareConfig:
    ../network/config/bond-with-vlans/compute-e1.yaml
  OS::TripleO::ComputeEdge1vdu::Net::SoftwareConfig:
    ../network/config/bond-with-vlans/compute-e1vdu.yaml

parameter_defaults:

  RootStackName: central

  NeutronBridgeMappings:
    - tenant:br-tenant
    - mgmt-edge1:br-edge1

  ComputeEdge1ControlPlaneSubnet: edge1
  ComputeEdge1vduControlPlaneSubnet: edge1
  OvercloudComputeEdge1Flavor: compute-edge1
  OvercloudComputeEdge1vduFlavor: compute-edge1vdu
  ComputeEdge1Count: 1
  ComputeEdge1vduCount: 1

  ComputeEdge1Parameters:
    NovaComputeAvailabilityZone: edge1
    KernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=128 intel_iommu=on iommu=pt"
    IsolCpusList: 2-35,38-71
    NovaComputeCpuDedicatedSet: 2-35,38-71
    NovaComputeCpuSharedSet: 0,1,36,37
    NovaEnableRbdBackend: false
    NeutronPhysicalDevMappings:
      - sriov-edge1-1:ens3f0
      - sriov-edge1-2:ens3f1
      - sriov-edge1-1:ens7f0
      - sriov-edge1-2:ens7f1
    NeutronSriovNumVFs:
      - ens3f0:8
      - ens3f1:8
      - ens7f0:8
      - ens7f1:8
    NovaPCIPassthrough:
      - devname: "ens3f0"
        physical_network: "sriov-edge1-1"
      - devname: "ens3f1"
        physical_network: "sriov-edge1-2"
      - devname: "ens7f0"
        physical_network: "sriov-edge1-1"
      - devname: "ens7f1"
        physical_network: "sriov-edge1-2"

  ComputeEdge1ExtraConfig:
    nova::cpu_allocation_ratio: 1
    nova::compute::resume_guests_state_on_host_boot: true
    nova::compute::libvirt::libvirt_cpu_model: host-passthrough
    nova::compute::libvirt::libvirt_cpu_model_extra_flags: host-tsc-deadline
    nova::compute::libvirt::mem_stats_period_seconds: 0

  ComputeEdge1vduImage: "overcloud-realtime-compute"
  ComputeEdge1vduParameters:
    NovaComputeAvailabilityZone: edge1vdu
    KernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=128 nx_huge_pages_recovery_ratio=0 intel_iommu=on iommu=pt elevator=cfq audit=1 nomodeset intel_idle.max_cstate=1 tsc=reliable idle=poll rcu_nocb_poll=1 clocksource=tsc pcie_aspm.policy=performance"
    IsolCpusList: 2-35,38-71
    NovaComputeCpuDedicatedSet: 2-35,38-71
    NovaComputeCpuSharedSet: 0,1,36,37
    NovaEnableRbdBackend: false
    NeutronPhysicalDevMappings:
      - fronthaul-edge1-1:ens1f0
      - fronthaul-edge1-2:ens1f1
      - fronthaul-edge1-1:ens4f0
      - fronthaul-edge1-2:ens4f1
      - sriov-edge1-1:ens3f0
      - sriov-edge1-2:ens3f1
      - sriov-edge1-1:ens8f0
      - sriov-edge1-2:ens8f1
    NeutronSriovNumVFs:
      - ens3f0:8
      - ens3f1:8
      - ens8f0:8
      - ens8f1:8
      - ens1f0:8
      - ens1f1:8
      - ens4f0:8
      - ens4f1:8
    NovaPCIPassthrough:
      - devname: "ens1f0"
        physical_network: "fronthaul-edge1-1"
      - devname: "ens1f1"
        physical_network: "fronthaul-edge1-2"
      - devname: "ens4f0"
        physical_network: "fronthaul-edge1-1"
      - devname: "ens4f1"
        physical_network: "fronthaul-edge1-2"
      - devname: "ens3f0"
        physical_network: "sriov-edge1-1"
      - devname: "ens3f1"
        physical_network: "sriov-edge1-2"
      - devname: "ens8f0"
        physical_network: "sriov-edge1-1"
      - devname: "ens8f1"
        physical_network: "sriov-edge1-2"
      - vendor_id: "1172"
        product_id: "5050"

  ComputeEdge1vduExtraConfig:
    nova::cpu_allocation_ratio: 1
    nova::compute::resume_guests_state_on_host_boot: true
    nova::pci::aliases:
      - name: vc_fpga
        vendor_id: '1172'
        product_id: '5050'
        device_type: 'type-VF'