resource_registry:
# Configure Networks

  OS::TripleO::ComputeEdge2::Net::SoftwareConfig:
    ../network/config/bond-with-vlans/compute-e2.yaml
  OS::TripleO::ComputeEdge2vdu::Net::SoftwareConfig:
    ../network/config/bond-with-vlans/compute-e2vdu.yaml

parameter_defaults:

  NovaComputeAvailabilityZone: edge2
  RootStackName: central

  ComputeEdge2ControlPlaneSubnet: edge2
  ComputeEdge2vduControlPlaneSubnet: edge2
  OvercloudComputeEdge2Flavor: compute-edge2
  OvercloudComputeEdge2vduFlavor: compute-edge2vdu
  ComputeEdge2Count: 1
  ComputeEdge2vduCount: 1

  ComputeEdge2Parameters:
    KernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=128 intel_iommu=on iommu=pt"
    IsolCpusList: 2-35,38-71
    NovaComputeCpuDedicatedSet: 2-35,38-71
    NovaComputeCpuSharedSet: 0,1,36,37
    NovaEnableRbdBackend: false
    NeutronPhysicalDevMappings:
      - sriov-edge2-1:ens3f0
      - sriov-edge2-2:ens3f1
      - sriov-edge2-1:ens7f0
      - sriov-edge2-2:ens7f1
    NeutronSriovNumVFs:
      - ens3f0:8
      - ens3f1:8
      - ens7f0:8
      - ens7f1:8
    NovaPCIPassthrough:
      - devname: "ens3f0"
        physical_network: "sriov-edge2-1"
      - devname: "ens3f1"
        physical_network: "sriov-edge2-2"
      - devname: "ens7f0"
        physical_network: "sriov-edge2-1"
      - devname: "ens7f1"
        physical_network: "sriov-edge2-2"

  ComputeEdge2ExtraConfig:
    nova::cpu_allocation_ratio: 1
    nova::compute::resume_guests_state_on_host_boot: true
    nova::compute::libvirt::libvirt_cpu_model: host-passthrough
    nova::compute::libvirt::libvirt_cpu_model_extra_flags: host-tsc-deadline
    nova::compute::libvirt::mem_stats_period_seconds: 0

  ComputeEdge2vduImage: "overcloud-realtime-compute"
  ComputeEdge2vduParameters:
    KernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=128 nx_huge_pages_recovery_ratio=0 intel_iommu=on iommu=pt elevator=cfq audit=1 nomodeset intel_idle.max_cstate=1 tsc=reliable idle=poll rcu_nocb_poll=1 clocksource=tsc pcie_aspm.policy=performance"
    IsolCpusList: 2-35,38-71
    NovaComputeCpuDedicatedSet: 2-35,38-71
    NovaComputeCpuSharedSet: 0,1,36,37
    NovaEnableRbdBackend: false
    NeutronPhysicalDevMappings:
      - fronthaul-edge2-1:ens1f0
      - fronthaul-edge2-2:ens1f1
      - fronthaul-edge2-1:ens4f0
      - fronthaul-edge2-2:ens4f1
      - sriov-edge2-1:ens3f0
      - sriov-edge2-2:ens3f1
      - sriov-edge2-1:ens8f0
      - sriov-edge2-2:ens8f1
    NeutronSriovNumVFs:
      - ens3f0:8
      - ens3f1:8
      - ens8f0:8
      - ens8f1:8
      - ens1f0:8
      - ens1f1:8
      - ens4f0:8
      - ens4f1:8
    NovaPCIPassthrough:
      - devname: "ens1f0"
        physical_network: "fronthaul-edge2-1"
      - devname: "ens1f1"
        physical_network: "fronthaul-edge2-2"
      - devname: "ens4f0"
        physical_network: "fronthaul-edge2-1"
      - devname: "ens4f1"
        physical_network: "fronthaul-edge2-2"
      - devname: "ens3f0"
        physical_network: "sriov-edge2-1"
      - devname: "ens3f1"
        physical_network: "sriov-edge2-2"
      - devname: "ens8f0"
        physical_network: "sriov-edge2-1"
      - devname: "ens8f1"
        physical_network: "sriov-edge2-2"
      - vendor_id: "1172"
        product_id: "5050"

  ComputeEdge2vduExtraConfig:
    nova::cpu_allocation_ratio: 1
    nova::compute::resume_guests_state_on_host_boot: true
    nova::pci::aliases:
      - name: vc_fpga
        vendor_id: '1172'
        product_id: '5050'
        device_type: 'type-VF'
