parameter_defaults:

  DnsServers:
  - 172.17.118.8
  NtpServer:
  - 172.17.118.1
  - 172.17.118.3
  - 172.17.118.5
  BondInterfaceOvsOptions: "mode=4 miimon=100"

  DockerInsecureRegistryAddress:
  - 172.17.118.8:5000
  - satellite.lab.roskosb.info:5000

  NeutronNetworkVLANRanges:
    - ovs-provider:117:117
    - ovs-provider-edge1:1117:1117
    - ovs-provider-edge2:2117:2117
    - sriov1:200:300
    - sriov2:200:300
    - sriov1-edge1:1200:1300
    - sriov2-edge1:1200:1300
    - sriov1-edge2:2200:2300
    - sriov2-edge2:2200:2300
    - fronthaul1:203:203
    - fronthaul2:203:203
    - fronthaul1-edge1:1203:1203
    - fronthaul2-edge1:1203:1203
    - fronthaul1-edge2:2203:2203
    - fronthaul2-edge2:2203:2203
  NeutronFlatNetworks:
    - floating-ips

  CloudName: overcloud.lab.roskosb.info
  CloudDomain: lab.local

  NovaReservedHostMemory: 4096

  NeutronEnableIsolatedMetadata: true
  NeutronEnableForceMetadata: true
  NeutronEnableMetadataNetwork: true
#  NeutronGlobalPhysnetMtu: 9000

  RhsmVars:
    rhsm_method: "satellite"
    rhsm_server_hostname: "satellite.lab.roskosb.info"
    rhsm_baseurl: "https://satellite.lab.roskosb.info/pulp/repos"
    rhsm_activation_key: "osp16-dev"
    rhsm_org_id: "lab"
    rhsm_force_register: True
