resource_registry:
# Configure Networks

  OS::TripleO::ComputeSriovEdge1::Net::SoftwareConfig:
    ../network/config/bond-with-vlans/computeSriov-edge.yaml
  OS::TripleO::ComputeVduEdge1::Net::SoftwareConfig:
    ../network/config/bond-with-vlans/computeVdu.yaml
  OS::TripleO::ComputeCentral::Net::SoftwareConfig:
    ../network/config/multiple-nics/compute.yaml

parameter_defaults:

  NovaComputeAvailabilityZone: edge1
  RootStackName: central

  NeutronBridgeMappings:
    - tenant:br-tenant
    - ovs-edge1:br-provider

  ComputeSriovEdge1ControlPlaneSubnet: edge1
  ComputeVduEdge1ControlPlaneSubnet: edge1
  OvercloudComputeSriovEdge1Flavor: computeSriov-edge1
  OvercloudComputeVduEdge1Flavor: computeVdu-edge1
  ComputeSriovEdge1Count: 1
  ComputeVduEdge1Count: 1

  ComputeEdge1ControlPlaneSubnet: edge1
  OvercloudComputeEdge1Flavor: compute-edge1
  ComputeEdge1Count: 1

  ComputeEdge1Parameters:
    NovaEnableRbdBackend: false

  ComputeSriovEdge1Parameters:
    KernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=350 intel_iommu=on iommu=pt"
    IsolCpusList: 2-35,38-71
    NovaComputeCpuDedicatedSet: 2-35,38-71
    NovaComputeCpuSharedSet: 0,1,36,37
    NovaEnableRbdBackend: false
    NeutronPhysicalDevMappings:
      - sriov1-edge1:ens3f0
      - sriov2-edge1:ens3f1
      - sriov1-edge1:ens7f0
      - sriov2-edge1:ens7f1
    NeutronSriovNumVFs:
      - ens3f0:8
      - ens3f1:8
      - ens7f0:8
      - ens7f1:8
    NovaPCIPassthrough:
      - devname: "ens3f0"
        physical_network: "sriov1-edge1"
      - devname: "ens3f1"
        physical_network: "sriov2-edge1"
      - devname: "ens7f0"
        physical_network: "sriov1-edge1"
      - devname: "ens7f1"
        physical_network: "sriov2-edge1"

  ComputeSriovEdge1ExtraConfig:
    nova::cpu_allocation_ratio: 1
    nova::compute::resume_guests_state_on_host_boot: true

  ComputeVduEdge1Image: "overcloud-realtime-compute"
  ComputeVduEdge1Parameters:
    KernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=350 nx_huge_pages_recovery_ratio=0 intel_iommu=on iommu=pt elevator=cfq audit=1 nomodeset intel_idle.max_cstate=1 tsc=reliable rcu_nocb_poll=1 clocksource=tsc pcie_aspm.policy=performance"
    IsolCpusList:  2-39,42-79
    NovaComputeCpuDedicatedSet:  2-39,42-79
    NovaComputeCpuSharedSet:  0,1,40,41
    NovaEnableRbdBackend: false
    NeutronPhysicalDevMappings:
      - fronthaul1-edge1:ens1f0
      - fronthaul2-edge1:ens1f1
      - fronthaul1-edge1:ens4f0
      - fronthaul2-edge1:ens4f1
      - sriov1-edge1:ens3f0
      - sriov2-edge1:ens3f1
      - sriov1-edge1:ens8f0
      - sriov2-edge1:ens8f1
    NeutronSriovNumVFs:
      - ens3f0:4
      - ens3f1:4
      - ens8f0:4
      - ens8f1:4
      - ens1f0:2
      - ens1f1:2
      - ens4f0:2
      - ens4f1:2
    NovaPCIPassthrough:
      - devname: "ens1f0"
        physical_network: "fronthaul1-edge1"
      - devname: "ens1f1"
        physical_network: "fronthaul2-edge1"
      - devname: "ens4f0"
        physical_network: "fronthaul1-edge1"
      - devname: "ens4f1"
        physical_network: "fronthaul2-edge1"
      - devname: "ens3f0"
        physical_network: "sriov1-edge1"
      - devname: "ens3f1"
        physical_network: "sriov2-edge1"
      - devname: "ens8f0"
        physical_network: "sriov1-edge1"
      - devname: "ens8f1"
        physical_network: "sriov2-edge1"
      - vendor_id: "1172"
        product_id: "5050"

  ComputeVduEdge1ExtraConfig:
    nova::cpu_allocation_ratio: 1
    nova::compute::resume_guests_state_on_host_boot: true
    nova::pci::aliases:
      - name: vc_fpga
        vendor_id: '1172'
        product_id: '5050'
        device_type: 'type-VF'
