resource_registry:
# Configure Networks
  OS::TripleO::Controller::Net::SoftwareConfig:
    ../network/config/multiple-nics/controller.yaml
  OS::TripleO::Compute::Net::SoftwareConfig:
    ../network/config/bond-with-vlans/compute.yaml
  OS::TripleO::ComputeHCI::Net::SoftwareConfig:
    ../network/config/bond-with-vlans/compute-hci.yaml

parameter_defaults:

  ControllerControlPlaneSubnet: ctlplane-subnet
  ComputeControlPlaneSubnet: ctlplane-subnet
  ComputeHCIControlPlaneSubnet: ctlplane-subnet
  VipSubnetMap:
    ctlplane: ctlplane-subnet
  OvercloudControllerFlavor: control
  OvercloudComputeFlavor: compute
  OvercloudComputeHCIFlavor: compute-hci
  ControllerCount: 3
  ComputeCount: 0
  ComputeHCICount: 3

  NovaSchedulerDefaultFilters:
    - RetryFilter
    - AvailabilityZoneFilter
    - ComputeFilter
    - AggregateInstanceExtraSpecsFilter
    - ComputeCapabilitiesFilter
    - ImagePropertiesFilter
    - ServerGroupAntiAffinityFilter
    - ServerGroupAffinityFilter
    - PciPassthroughFilter
    - NUMATopologyFilter

  PublicVirtualFixedIPs: [{'ip_address':'172.17.119.10'}]

  ControllerExtraConfig:
    nova::cpu_allocation_ratio: 1
    nova::pci::aliases:
      - name: vc_fpga
        vendor_id: '1172'
        product_id: '5050'
        device_type: 'type-VF'

  ComputeParameters:
    KernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=128 intel_iommu=on iommu=pt"
    IsolCpusList: 2-35,38-71
    NovaComputeCpuDedicatedSet: 2-35,38-71
    NovaComputeCpuSharedSet: 0,1,36,37
    NeutronPhysicalDevMappings:
      - sriov-1:ens3f0
      - sriov-2:ens3f1
      - sriov-1:ens7f0
      - sriov-2:ens7f1
    NeutronSriovNumVFs:
      - ens3f0:8
      - ens3f1:8
      - ens7f0:8
      - ens7f1:8
    NovaPCIPassthrough:
      - devname: "ens3f0"
        physical_network: "sriov-1"
      - devname: "ens3f1"
        physical_network: "sriov-2"
      - devname: "ens7f0"
        physical_network: "sriov-1"
      - devname: "ens7f1"
        physical_network: "sriov-2"

  ComputeExtraConfig:
    nova::cpu_allocation_ratio: 1
    nova::compute::resume_guests_state_on_host_boot: true

  ComputeHCIParameters:
    KernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=128 intel_iommu=on iommu=pt"
    IsolCpusList: 2-35,38-71
    NovaComputeCpuDedicatedSet: 6-35,42-71
    NovaComputeCpuSharedSet: 0,1,36,37
    NovaReservedHostMemory: 30720
    NeutronPhysicalDevMappings:
      - sriov-1:ens3f0
      - sriov-2:ens3f1
      - sriov-1:ens7f0
      - sriov-2:ens7f1
    NeutronSriovNumVFs:
      - ens3f0:8
      - ens3f1:8
      - ens7f0:8
      - ens7f1:8
    NovaPCIPassthrough:
      - devname: "ens3f0"
        physical_network: "sriov-1"
      - devname: "ens3f1"
        physical_network: "sriov-2"
      - devname: "ens7f0"
        physical_network: "sriov-1"
      - devname: "ens7f1"
        physical_network: "sriov-2"

  ComputeHCIExtraConfig:
    nova::cpu_allocation_ratio: 1
    nova::compute::resume_guests_state_on_host_boot: true



