resource_registry:
  OS::TripleO::Services::NovaAZConfig: OS::Heat::None

parameter_defaults:

  DnsServers:
  - 172.17.118.6
  NtpServer:
  - 172.17.118.15

  BondInterfaceOvsOptions: "mode=4 miimon=100"

  DockerInsecureRegistryAddress:
  - 172.17.118.6:5000
  - satellite2.lab.roskosb.info:5000

  NeutronNetworkVLANRanges:
    - ovs-central:117:117
    - ovs-edge1:1117:1117
    - ovs-edge2:2117:2117
    - sriov1-central:204:300
    - sriov2-central:204:300
    - sriov1-edge1:1204:1300
    - sriov2-edge1:1204:1300
    - sriov1-edge2:2204:2300
    - sriov2-edge2:2204:2300
    - fronthaul1-central:203:203
    - fronthaul2-central:203:203
    - fronthaul1-edge1:1203:1203
    - fronthaul2-edge1:1203:1203
    - fronthaul1-edge2:2203:2203
    - fronthaul2-edge2:2203:2203
  NeutronFlatNetworks:
    - floating-ips

  CloudName: overcloud.lab.roskosb.info
  CloudDomain: lab.local

  NovaReservedHostMemory: 4096

  NeutronEnableIsolatedMetadata: true
  NeutronEnableForceMetadata: true
  NeutronEnableMetadataNetwork: true
#  NeutronGlobalPhysnetMtu: 9000

  RhsmVars:
    rhsm_method: "satellite"
    rhsm_server_hostname: "satellite2.lab.roskosb.info"
    rhsm_baseurl: "https://satellite2.lab.roskosb.info/pulp/repos"
    rhsm_activation_key: "osp16-1-dev-overcloud"
    rhsm_org_id: "Default"
    rhsm_force_register: True
