resource_registry:
# Configure Networks

  OS::TripleO::ComputeSriovEdge2::Net::SoftwareConfig:
    ../network/config/bond-with-vlans/computeSriov-edge.yaml
  OS::TripleO::ComputeVduEdge2::Net::SoftwareConfig:
    ../network/config/bond-with-vlans/computeVdu.yaml
  OS::TripleO::ComputeCentral::Net::SoftwareConfig:
    ../network/config/multiple-nics/compute.yaml

parameter_defaults:

  NovaComputeAvailabilityZone: edge2
  RootStackName: central

  NeutronBridgeMappings:
    - tenant:br-tenant
    - ovs-edge2:br-provider

  ComputeSriovEdge2ControlPlaneSubnet: edge2
  ComputeVduEdge2ControlPlaneSubnet: edge2
  OvercloudComputeSriovEdge2Flavor: computeSriov-edge2
  OvercloudComputeVduEdge2Flavor: computeVdu-edge2
  ComputeSriovEdge2Count: 1
  ComputeVduEdge2Count: 1

  ComputeEdge2ControlPlaneSubnet: edge2
  OvercloudComputeEdge2Flavor: compute-edge2
  ComputeEdge2Count: 1

  ComputeEdge2Parameters:
    NovaEnableRbdBackend: false

  ComputeSriovEdge2Parameters:
    KernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=350 intel_iommu=on iommu=pt"
    IsolCpusList: 2-35,38-71
    # switch to NovaVcpuPinSet as work around for bz-1835705
    # NovaComputeCpuDedicatedSet: 2-35,38-71
    NovaVcpuPinSet: 2-35,38-71
    NovaComputeCpuSharedSet: 0,1,36,37
    NovaEnableRbdBackend: false
    NeutronPhysicalDevMappings:
      - sriov1-edge2:ens3f0
      - sriov2-edge2:ens3f1
      - sriov1-edge2:ens7f0
      - sriov2-edge2:ens7f1
    NeutronSriovNumVFs:
      - ens3f0:8
      - ens3f1:8
      - ens7f0:8
      - ens7f1:8
    NovaPCIPassthrough:
      - devname: "ens3f0"
        physical_network: "sriov1-edge2"
      - devname: "ens3f1"
        physical_network: "sriov2-edge2"
      - devname: "ens7f0"
        physical_network: "sriov1-edge2"
      - devname: "ens7f1"
        physical_network: "sriov2-edge2"

  ComputeSriovEdge2ExtraConfig:
    nova::cpu_allocation_ratio: 1
    nova::compute::resume_guests_state_on_host_boot: true

  ComputeVduEdge2Image: "overcloud-realtime-compute"
  ComputeVduEdge2Parameters:
    KernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=350 nx_huge_pages_recovery_ratio=0 intel_iommu=on iommu=pt elevator=cfq audit=1 nomodeset intel_idle.max_cstate=1 tsc=reliable rcu_nocb_poll=1 clocksource=tsc pcie_aspm.policy=performance"
    IsolCpusList:  2-39,42-79
    # switch to NovaVcpuPinSet as work around for bz-1835705
    #NovaComputeCpuDedicatedSet:  2-39,42-79
    NovaVcpuPinSet: 2-39,42-79
    NovaComputeCpuSharedSet:  0,1,40,41
    NovaEnableRbdBackend: false
    NeutronPhysicalDevMappings:
      - fronthaul1-edge2:p1p1
      - fronthaul2-edge2:p1p3
      - fronthaul1-edge2:p4p1
      - fronthaul2-edge2:p4p3
      - sriov1-edge2:p3p1
      - sriov2-edge2:p3p2
      - sriov1-edge2:p8p1
      - sriov2-edge2:p8p2
    NeutronSriovNumVFs:
      - p3p1:4
      - p3p2:4
      - p8p1:4
      - p8p2:4
      - p1p1:2
      - p1p3:2
      - p4p1:2
      - p4p3:2
    NovaPCIPassthrough:
      - devname: "p1p1"
        physical_network: "fronthaul1-edge2"
      - devname: "p1p3"
        physical_network: "fronthaul2-edge2"
      - devname: "p4p1"
        physical_network: "fronthaul1-edge2"
      - devname: "p4p3"
        physical_network: "fronthaul2-edge2"
      - devname: "p3p1"
        physical_network: "sriov1-edge2"
      - devname: "p3p2"
        physical_network: "sriov2-edge2"
      - devname: "p8p1"
        physical_network: "sriov1-edge2"
      - devname: "p8p2"
        physical_network: "sriov2-edge2"
      - vendor_id: "1172"
        product_id: "5050"

  ComputeVduEdge2ExtraConfig:
    nova::cpu_allocation_ratio: 1
    nova::compute::resume_guests_state_on_host_boot: true
    nova::pci::aliases:
      - name: vc_fpga
        vendor_id: '1172'
        product_id: '5050'
        device_type: 'type-VF'
