heat_template_version: queens
description: >
  Software Config to drive os-net-config to configure VLANs for the ComputeEdge2 role.
parameters:
  ControlPlaneIp:
    default: ''
    description: IP address/subnet on the ctlplane network
    type: string
  StorageIpSubnet:
    default: ''
    description: IP address/subnet on the storage network
    type: string
  StorageMgmtIpSubnet:
    default: ''
    description: IP address/subnet on the storage_mgmt network
    type: string
  InternalApiIpSubnet:
    default: ''
    description: IP address/subnet on the internal_api network
    type: string
  TenantIpSubnet:
    default: ''
    description: IP address/subnet on the tenant network
    type: string
  ExternalIpSubnet:
    default: ''
    description: IP address/subnet on the external network
    type: string
  InternalApiEdge1IpSubnet:
    default: ''
    description: IP address/subnet on the internal_api_edge1 network
    type: string
  TenantEdge1IpSubnet:
    default: ''
    description: IP address/subnet on the tenant_edge1 network
    type: string
  InternalApiEdge2IpSubnet:
    default: ''
    description: IP address/subnet on the internal_api_edge2 network
    type: string
  TenantEdge2IpSubnet:
    default: ''
    description: IP address/subnet on the tenant_edge2 network
    type: string
  StorageNetworkVlanID:
    default: 170
    description: Vlan ID for the storage network traffic.
    type: number
  StorageMgmtNetworkVlanID:
    default: 180
    description: Vlan ID for the storage_mgmt network traffic.
    type: number
  InternalApiNetworkVlanID:
    default: 130
    description: Vlan ID for the internal_api network traffic.
    type: number
  TenantNetworkVlanID:
    default: 201
    description: Vlan ID for the tenant network traffic.
    type: number
  ExternalNetworkVlanID:
    default: 119
    description: Vlan ID for the external network traffic.
    type: number
  InternalApiEdge1NetworkVlanID:
    default: 1130
    description: Vlan ID for the internal_api_edge1 network traffic.
    type: number
  TenantEdge1NetworkVlanID:
    default: 1201
    description: Vlan ID for the tenant_edge1 network traffic.
    type: number
  InternalApiEdge2NetworkVlanID:
    default: 2130
    description: Vlan ID for the internal_api_edge2 network traffic.
    type: number
  TenantEdge2NetworkVlanID:
    default: 2201
    description: Vlan ID for the tenant_edge2 network traffic.
    type: number
  ControlPlaneSubnetCidr: # Override this via parameter_defaults
    default: '24'
    description: The subnet CIDR of the control plane network.
    type: string
  ControlPlaneDefaultRoute: # Override this via parameter_defaults
    description: The default route of the control plane network.
    type: string
  ExternalInterfaceDefaultRoute:
    default: '172.17.119.62'
    description: default route for the external network
    type: string
  DnsServers: # Override this via parameter_defaults
    default: []
    description: A list of DNS servers (2 max for some implementations) that will be added to resolv.conf.
    type: comma_delimited_list
  EC2MetadataIp: # Override this via parameter_defaults
    description: The IP address of the EC2 metadata server.
    type: string
  DnsSearchDomains: # Override this via parameter_defaults
    default: []
    description: A list of DNS search domains to be added (in order) to resolv.conf.
    type: comma_delimited_list
resources:
  OsNetConfigImpl:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config:
        str_replace:
          template:
            get_file: ../../scripts/run-os-net-config.sh
          params:
            $network_config:
              network_config:
              - type: ovs_bridge
                name: bridge_name
                use_dhcp: false
                dns_servers:
                  get_param: DnsServers
                domain:
                  get_param: DnsSearchDomains
                addresses:
                - ip_netmask:
                    list_join:
                    - /
                    - - get_param: ControlPlaneIp
                      - get_param: ControlPlaneSubnetCidr
                routes:
                - ip_netmask: 169.254.169.254/32
                  next_hop:
                    get_param: EC2MetadataIp
                - default: true
                  next_hop:
                    get_param: ControlPlaneDefaultRoute
                members:
                - type: interface
                  name: nic1
                  # force the MAC address of the bridge to this interface
                  primary: true
                - type: vlan
                  vlan_id:
                    get_param: InternalApiEdge2NetworkVlanID
                  addresses:
                  - ip_netmask:
                      get_param: InternalApiEdge2IpSubnet
                - type: vlan
                  vlan_id:
                    get_param: TenantEdge2NetworkVlanID
                  addresses:
                  - ip_netmask:
                      get_param: TenantEdge2IpSubnet
outputs:
  OS::stack_id:
    description: The OsNetConfigImpl resource.
    value:
      get_resource: OsNetConfigImpl